name: Build EXE Multi-OS
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
  
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
  
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --only-binary=all -r requirements.txt --timeout 600
          pip install pyinstaller
  
      - name: Build EXE with PyInstaller
        run: |
          cd code
          pyinstaller --onefile --windowed --noconsole --add-data "data;data" --name "STIX Solor Orbiter" --paths=src --hidden-import matplotlib.backends.backend_tkagg src/main.py
  
      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: dist/*.exe
          
  build-unix:
    runs-on:  ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
  
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
  
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --only-binary=all -r requirements.txt --timeout 600
          pip install pyinstaller
  
      - name: Build binary with PyInstaller
        run: |
          cd code
          pyinstaller --onefile --windowed --noconsole \
            --add-data "data:data" \
            --name "STIX-Solar-Orbiter" \
            --paths=src \
            --hidden-import matplotlib.backends.backend_tkagg \
            src/main.py
  
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-latest-binary
          path: dist/*
          
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
          
      - name: Create macos app
        run: |
            cd code
            pyinstaller \
            --windowed \
            --name "STIX-Solar-Orbiter" \
            --add-data "data:data" \
            --paths=src \
            --hidden-import matplotlib.backends.backend_tkagg \
            src/main.py

      - name: Create macOS DMG
        run: |
          cd code/
          mkdir dmg
          cp -R dist/STIX-Solar-Orbiter.app dmg/
          hdiutil create \
            -volname "STIX Solar Orbiter" \
            -srcfolder dmg \
            -ov \
            -format UDZO \
            dist/STIX-Solar-Orbiter.dmg
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-latest-artifact
          path: |
            dist/STIX-Solar-Orbiter.dmg
  
